[{'id': 0,
  'name': 'Additional Products',
  'type': {'keyName': 'ADDITIONAL_SERVICES'}},
 {'id': 10,
  'name': 'Control Panels for VPS',
  'type': {'keyName': 'VPS_CONTROL_PANEL'}},
 {'description': 'Virtual Server Instance',
  'id': 46,
  'name': 'Cloud Server',
  'type': {'keyName': 'VIRTUAL_SERVER_INSTANCE'}},
 {'id': 50,
  'name': 'Bare Metal Instance',
  'type': {'keyName': 'BARE_METAL_CORE'}},
 {'id': 56,
  'name': 'Quad Processor Multi Core Nehalem EX',
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'description': '<div class="PageTopicSubHead">Colocation Service</div>',
  'id': 58,
  'name': 'Colocation Service',
  'type': {'keyName': 'COLOCATION'}},
 {'id': 126,
  'name': 'Single Xeon 1200 Series (Sandy Bridge / Haswell)',
  'server': ['Single Intel Xeon E3-1270 v3 (4 Cores, 3.50 GHz)',
             'Single Intel Xeon E3-1270 (4 Cores, 3.40 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'id': 142,
  'name': 'Single Xeon 2000 Series (Sandy Bridge)',
  'server': ['Single Intel Xeon E5-2620 (6 Cores, 2.00 GHz)',
             'Single Intel Xeon E5-2690 (8 Cores, 2.90 GHz)',
             'Single Intel Xeon E5-2650 (8 Cores, 2.00 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'id': 143,
  'name': 'Dual Xeon 2000 Series (Sandy Bridge)',
  'server': ['Dual Intel Xeon E5-2650 (16 Cores, 2.00 GHz)',
             'Dual Intel Xeon E5-2620 (12 Cores, 2.00 GHz)',
             'Dual Intel Xeon E5-2690 (16 Cores, 2.90 GHz)',
             'Dual Intel Xeon E5-2650 v3 (20 Cores, 2.30 GHz)',
             'Dual Intel Xeon E5-2690 v3 (24 Cores, 2.60 GHz)',
             'Dual Intel Xeon E5-2620 v3 (12 Cores, 2.40 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'id': 144,
  'name': 'Specialty Server: GPU',
  'server': ['Dual Intel Xeon E5-2650 (16 Cores, 2.00 GHz)',
             'Dual Intel Xeon E5-2690 (16 Cores, 2.90 GHz)',
             'Dual Intel Xeon E5-2620 (12 Cores, 2.00 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'id': 146,
  'name': 'Sandy Bridge 1270',
  'server': ['Single Intel Xeon E3-1270 (4 Cores, 3.40 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'id': 147,
  'name': 'Specialty Server: 4u Mass Storage Dual Xeon 2000 (Sandy Bridge) Series',
  'server': ['Dual Intel Xeon E5-2650 v3 (20 Cores, 2.30 GHz)',
             'Dual Intel Xeon E5-2650 (16 Cores, 2.00 GHz)',
             'Dual Intel Xeon E5-2690 v3 (24 Cores, 2.60 GHz)',
             'Dual Intel Xeon E5-2620 v3 (12 Cores, 2.40 GHz)',
             'Dual Intel Xeon E5-2690 (16 Cores, 2.90 GHz)',
             'Dual Intel Xeon E5-2620 (12 Cores, 2.00 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'id': 148,
  'name': 'Specialty Server: 2u Mass Storage Dual Xeon 2000 (Sandy Bridge) Series',
  'server': ['Dual Intel Xeon E5-2690 v3 (24 Cores, 2.60 GHz)',
             'Dual Intel Xeon E5-2650 (16 Cores, 2.00 GHz)',
             'Dual Intel Xeon E5-2620 (12 Cores, 2.00 GHz)',
             'Dual Intel Xeon E5-2690 (16 Cores, 2.90 GHz)',
             'Dual Intel Xeon E5-2620 v3 (12 Cores, 2.40 GHz)',
             'Dual Intel Xeon E5-2650 v3 (20 Cores, 2.30 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'id': 158,
  'name': 'Quad Xeon 4000 Series (Sandy Bridge)',
  'server': ['Quad Intel Xeon E5-4650 (32 Cores, 2.70 GHz)',
             'Quad Intel Xeon E5-4620 (32 Cores, 2.20 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'id': 173, 'name': 'VHD Import', 'type': {'keyName': 'VHD_IMPORT'}},
 {'description': 'Network Gateway Appliance',
  'id': 174,
  'name': 'Network Gateway Appliance',
  'server': ['Single Intel Xeon E3-1270 (4 Cores, 3.40 GHz)',
             'Single Intel Xeon E3-1270 v3 (4 Cores, 3.50 GHz)'],
  'type': {'keyName': 'BARE_METAL_GATEWAY'}},
 {'id': 192,
  'name': 'Application Delivery Appliance',
  'type': {'keyName': 'ADDITIONAL_SERVICES_APPLICATION_DELIVERY_APPLIANCE'}},
 {'id': 194,
  'name': 'Load Balancers',
  'type': {'keyName': 'ADDITIONAL_SERVICES_LOAD_BALANCER'}},
 {'id': 196,
  'name': 'Network Gateway Appliance Cluster',
  'type': {'keyName': 'GATEWAY_RESOURCE_GROUP'}},
 {'id': 198,
  'name': 'Portable Storage',
  'type': {'keyName': 'ADDITIONAL_SERVICES_PORTABLE_STORAGE'}},
 {'description': 'Bare Metal Server',
  'id': 200,
  'name': 'Bare Metal Server',
  'server': ['Dual Intel Xeon E5-2650 (16 Cores, 2.00 GHz)',
             'Single Intel Xeon E3-1270 (4 Cores, 3.40 GHz)',
             'Single Intel Xeon E3-1270 v3 (4 Cores, 3.50 GHz)',
             'Dual Intel Xeon E5-2620 v4 (16 Cores, 2.10 GHz)',
             'Dual Intel Xeon E5-2620 v3 (12 Cores, 2.40 GHz)',
             'Dual Intel Xeon E5-2690 v4 (28 Cores, 2.60 GHz)',
             'Dual Intel Xeon E5-2620 v4 (16 Cores, 2.10 GHz)',
             'Dual Intel Xeon E5-2620 (12 Cores, 2.00 GHz)',
             'Dual Intel Xeon E5-2690 (16 Cores, 2.90 GHz)',
             'Dual Intel Xeon E5-2650 v3 (20 Cores, 2.30 GHz)',
             'Dual Intel Xeon E5-2690 v3 (24 Cores, 2.60 GHz)',
             'Dual Intel Xeon E5-2690 v4 (28 Cores, 2.60 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU_FAST_PROVISION'}},
 {'description': 'POWER8 TULETA FOR WATSON',
  'id': 202,
  'name': 'POWER8 TULETA',
  'type': {'keyName': 'BARE_METAL_POWER_CPU'}},
 {'id': 206,
  'name': 'Object Storage',
  'type': {'keyName': 'ADDITIONAL_SERVICES_OBJECT_STORAGE'}},
 {'id': 208,
  'name': 'Content Delivery Network',
  'type': {'keyName': 'ADDITIONAL_SERVICES_CDN'}},
 {'id': 210,
  'name': 'SSL Certificate',
  'type': {'keyName': 'ADDITIONAL_SERVICES_SSL_CERTIFICATE'}},
 {'id': 212,
  'name': 'Message Queue',
  'type': {'keyName': 'ADDITIONAL_SERVICES_MESSAGE_QUEUE'}},
 {'id': 216,
  'name': 'Network Attached Storage',
  'type': {'keyName': 'ADDITIONAL_SERVICES_NETWORK_ATTACHED_STORAGE'}},
 {'id': 218,
  'name': 'iSCSI Storage',
  'type': {'keyName': 'ADDITIONAL_SERVICES_ISCSI_STORAGE'}},
 {'id': 222,
  'name': 'Performance',
  'type': {'keyName': 'ADDITIONAL_SERVICES_PERFORMANCE_STORAGE'}},
 {'id': 226,
  'name': 'Authentication Services',
  'type': {'keyName': 'ADDITIONAL_SERVICES_AUTHENTICATION_SERVICES'}},
 {'id': 234,
  'name': 'Quad Xeon E7-4800 v2 (Ivy Bridge) Series',
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'description': 'Network Gateway Appliance (10 Gbps)',
  'id': 236,
  'name': 'Network Gateway Appliance (10 Gbps)',
  'server': ['Dual Intel Xeon E5-2620 (12 Cores, 2.00 GHz)',
             'Dual Intel Xeon E5-2690 v4 (28 Cores, 2.60 GHz)',
             'Dual Intel Xeon E5-2620 v4 (16 Cores, 2.10 GHz)',
             'Dual Intel Xeon E5-2690 (16 Cores, 2.90 GHz)',
             'Dual Intel Xeon E5-2650 v3 (20 Cores, 2.30 GHz)',
             'Dual Intel Xeon E5-2650 v4 (24 Cores, 2.20 GHz)',
             'Dual Intel Xeon E5-2650 (16 Cores, 2.00 GHz)',
             'Dual Intel Xeon E5-2690 v3 (24 Cores, 2.60 GHz)',
             'Dual Intel Xeon E5-2620 v3 (12 Cores, 2.40 GHz)'],
  'type': {'keyName': 'BARE_METAL_GATEWAY'}},
 {'id': 240,
  'name': 'Endurance',
  'type': {'keyName': 'ADDITIONAL_SERVICES_ENTERPRISE_STORAGE'}},
 {'description': 'POWER8 Servers',
  'id': 242,
  'name': 'POWER8 Servers',
  'server': ['Single POWER8 C812L (10 Cores, 3.49 GHz)',
             'Single POWER8 C812L (8 Cores, 3.85 GHz)'],
  'type': {'keyName': 'BARE_METAL_POWER_CPU'}},
 {'description': 'Monitoring',
  'id': 244,
  'name': 'Monitoring',
  'type': {'keyName': 'ADDITIONAL_SERVICES_MONITORING'}},
 {'id': 246,
  'name': 'Network Message Delivery',
  'type': {'keyName': 'ADDITIONAL_SERVICES_NETWORK_MESSAGE_DELIVERY'}},
 {'description': 'Dual E5-2600 v3 Series (36 Drives)',
  'id': 248,
  'name': 'Dual E5-2600 v3 Series (36 Drives)',
  'server': ['Dual Intel Xeon E5-2650 v3 (20 Cores, 2.30 GHz)',
             'Dual Intel Xeon E5-2690 v3 (24 Cores, 2.60 GHz)',
             'Dual Intel Xeon E5-2620 v3 (12 Cores, 2.40 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'id': 249,
  'name': 'Domain Name Services',
  'type': {'keyName': 'ADDITIONAL_SERVICES_DOMAIN_NAME_SERVICES'}},
 {'description': 'Dual E5-2600 v3 Series (12 Drives)',
  'id': 251,
  'name': 'Dual E5-2600 v3 Series (12 Drives)',
  'server': ['Dual Intel Xeon E5-2620 v3 (12 Cores, 2.40 GHz)',
             'Dual Intel Xeon E5-2650 v3 (20 Cores, 2.30 GHz)',
             'Dual Intel Xeon E5-2690 v3 (24 Cores, 2.60 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'description': 'Dual E5-2600 v3 Series (4 Drives)',
  'id': 253,
  'name': 'Dual E5-2600 v3 Series (4 Drives)',
  'server': ['Dual Intel Xeon E5-2620 v3 (12 Cores, 2.40 GHz)',
             'Dual Intel Xeon E5-2650 v3 (20 Cores, 2.30 GHz)',
             'Dual Intel Xeon E5-2690 v3 (24 Cores, 2.60 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'description': 'Single E3-1270 (4 Drives)',
  'id': 255,
  'name': 'Single E3-1270 (4 Drives)',
  'server': ['Single Intel Xeon E3-1270 (4 Cores, 3.40 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'description': 'Single E3-1270 (4 Drives)',
  'id': 257,
  'name': 'Single E3-1270 v3 (4 Drives)',
  'server': ['Single Intel Xeon E3-1270 v3 (4 Cores, 3.50 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'description': 'Single E5-2600 Series (4 Drives)',
  'id': 259,
  'name': 'Single E5-2600 Series (4 Drives)',
  'server': ['Single Intel Xeon E5-2650 (8 Cores, 2.00 GHz)',
             'Single Intel Xeon E5-2620 (6 Cores, 2.00 GHz)',
             'Single  Intel  Xeon  E5-2620 (6 Cores, 2.00 GHz)',
             'Single Intel Xeon E5-2690 (8 Cores, 2.90 GHz)',
             'Single  Intel  Xeon  E5-2690 (8 Cores, 2.90 GHz)',
             'Single  Intel  Xeon  E5-2650  (8 Cores, 2.00 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'description': 'Single E3-1270 (2 Drives)',
  'id': 261,
  'name': 'Single E3-1270 (2 Drives)',
  'server': ['Single Intel Xeon E3-1270 (4 Cores, 3.40 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'description': 'Dual E5-2600 Series (36 Drives)',
  'id': 263,
  'name': 'Dual E5-2600 Series (36 Drives)',
  'server': ['Dual Intel Xeon E5-2690 (16 Cores, 2.90 GHz)',
             'Dual Intel Xeon E5-2650 (16 Cores, 2.00 GHz)',
             'Dual Intel Xeon E5-2620 (12 Cores, 2.00 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'description': 'Dual E5-2600 Series (12 Drives)',
  'id': 265,
  'name': 'Dual E5-2600 Series (12 Drives)',
  'server': ['Dual Intel Xeon E5-2620 (12 Cores, 2.00 GHz)',
             'Dual Intel Xeon E5-2650 (16 Cores, 2.00 GHz)',
             'Dual Intel Xeon E5-2690 (16 Cores, 2.90 GHz)',
             'Dual Intel Xeon E5-2650 (16 Cores, 2.00 GHz)*',
             'Dual Intel Xeon E5-2690 (16 Cores, 2.90 GHz)*',
             'Dual Intel Xeon E5-2620 (12 Cores, 2.00 GHz) - Based on availability in DCs, contact sales'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'description': 'Quad E5-4600 Series (24 Drives)',
  'id': 267,
  'name': 'Quad E5-4600 Series (24 Drives)',
  'server': ['Quad Intel Xeon E5-4650 (32 Cores, 2.70 GHz)',
             'Quad Intel Xeon E5-4620 (32 Cores, 2.20 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'description': 'Quad E7-4800  Series (6 Drives)',
  'id': 269,
  'name': 'Quad E7-4800  Series (6 Drives)',
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'description': 'Quad E7-4800 v2 Series (24 Drives)',
  'id': 271,
  'name': 'Quad E7-4800 v2 Series (24 Drives)',
  'server': ['Quad Intel Xeon E7-4820 v2 (32 Cores, 2.00 GHz)',
             'Quad Intel Xeon E7-4850 v2 (48 Cores, 2.30 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'description': 'Dual E5-2600 (4 Drives)',
  'id': 273,
  'name': 'Dual E5-2600 (4 Drives)',
  'server': ['Dual Intel Xeon E5-2650 (16 Cores, 2.00 GHz)',
             'Dual Intel Xeon E5-2690 (16 Cores, 2.90 GHz)',
             'Dual Intel Xeon E5-2620 (12 Cores, 2.00 GHz)',
             'Dual Intel Xeon E5-2690 (16 Cores, 2.90 GHz)*',
             'Dual Intel Xeon E5-2650 (16 Cores, 2.00 GHz)*'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'id': 279,
  'name': 'Static IP Addresses',
  'type': {'keyName': 'ADDITIONAL_SERVICES_STATIC_IP_ADDRESSES'}},
 {'id': 281,
  'name': 'Portable IP Addresses',
  'type': {'keyName': 'ADDITIONAL_SERVICES_PORTABLE_IP_ADDRESSES'}},
 {'id': 283,
  'name': 'Hardware Security Module',
  'type': {'keyName': 'HARDWARE_SECURITY_MODULE'}},
 {'id': 293,
  'name': 'Paid Support',
  'type': {'keyName': 'ADDITIONAL_SERVICES_SUPPORT'}},
 {'description': 'SAP Certified Servers',
  'id': 295,
  'name': 'Certified Servers',
  'server': ['Quad Intel Xeon E7-4890 v2 (60 Cores, 2.80 GHz) -(Subject to availability - Please contact Sales to order)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'id': 301,
  'name': 'Software License Package',
  'type': {'keyName': 'ADDITIONAL_SERVICES_SOFTWARE_LICENSE'}},
 {'id': 303,
  'name': 'aPersona Adaptive Security Manager (ASM)',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 305, 'name': 'BlazeMeter', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 307, 'name': 'box', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 309,
  'name': 'ClearDB MySQL Database',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 311, 'name': 'CloudAMQP', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 313,
  'name': 'Cupenya Insights',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 315, 'name': 'DreamFace', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 317, 'name': 'ElephantSQL', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 319, 'name': 'flowthings.io', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 321, 'name': 'Geocoding', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 323, 'name': 'Hiptest', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 325,
  'name': 'IQP IoT Code-Free App Development',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 327, 'name': 'jKool', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 329, 'name': 'Kinetise', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 331, 'name': 'Load Impact', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 333,
  'name': 'Memcached Cloud',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 335, 'name': 'Moni.ai', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 337,
  'name': 'Namara.io Catalog',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 339, 'name': 'New Relic', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 341, 'name': 'PubNub', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 343,
  'name': 'Reappt from Push Technology',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 345, 'name': 'Redis Cloud', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 347,
  'name': 'Reverse Geocoding',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 349,
  'name': 'Rocket Mainframe Data',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 351, 'name': 'Searchly', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 353,
  'name': 'Simplicite aPaaS for Bluemix',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 355, 'name': 'Statica', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 357, 'name': 'TinyQueries', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 359,
  'name': 'Travel Boundary Service',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 361, 'name': 'Twilio', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 363, 'name': 'Ustream', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 365,
  'name': 'Validate Address',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 367, 'name': 'SendGrid', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 369, 'name': 'Access Trail', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 371, 'name': 'Active Deploy', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 373, 'name': 'AlchemyAPI', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 375, 'name': 'API Connect', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 377, 'name': 'API Harmony', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 379,
  'name': 'Application Security on Cloud',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 381,
  'name': 'Automated Accessibility Tester',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 383, 'name': 'Auto-Scaling', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 385, 'name': 'Blockchain', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 387,
  'name': 'Connect & Compose',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 389,
  'name': 'Content Delivery (CDN)',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 391,
  'name': 'Context Mapping',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 393,
  'name': 'Delivery Pipeline',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 395,
  'name': 'Digital Content Checker',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 397,
  'name': 'Document Generation',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 399,
  'name': 'Driver Behavior',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 401,
  'name': 'Elasticsearch by Compose',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 403,
  'name': 'Embeddable Reporting',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 405, 'name': 'Gamification', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 407,
  'name': 'Globalization Pipeline',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 409, 'name': 'IBM Graph', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 411,
  'name': 'IBM Identity Mixer',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 413,
  'name': 'IBM Push Notifications',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 415,
  'name': 'Insights for Twitter',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 417,
  'name': 'Insights for Weather',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 419,
  'name': 'Integration Testing',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 421,
  'name': 'Internet of Things Workbench',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 423,
  'name': 'IoT for Electronics',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 425,
  'name': 'IoT Real-Time Insights',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 427, 'name': 'Key Protect', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 429,
  'name': 'Message Connect',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 431,
  'name': 'Message Hub Incubator',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 433,
  'name': 'Mobile Client Access',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 435,
  'name': 'Mobile Foundation',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 437,
  'name': 'Mobile Quality Extensions',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 439,
  'name': 'MongoDB by Compose',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 441,
  'name': 'Monitoring and Analytics',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 443, 'name': 'Object Storage', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 445,
  'name': 'PostgreSQL by Compose',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 447,
  'name': 'Presence Insights',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 449,
  'name': 'Probabilistic Match',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 451,
  'name': 'Redis by Compose',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 453,
  'name': 'Relationship Extraction',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 455,
  'name': 'Service Discovery',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 457, 'name': 'Service Proxy', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 459, 'name': 'Tone Analyzer', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 461, 'name': 'Track & Plan', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 463,
  'name': 'Visual Insights',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 465,
  'name': 'Visual Recognition',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 467,
  'name': 'WebSphere Application Server',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 469,
  'name': 'XPages NoSQL Database',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 471, 'name': 'Apache Spark', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 473, 'name': 'API Management', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 475,
  'name': 'ASP.NET 5 for Bluemix',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 477, 'name': 'Business Rules', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 479,
  'name': 'Cloud Integration',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 481,
  'name': 'Cloudant NoSQL DB',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 483,
  'name': 'Concept Insights',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 485, 'name': 'dashDB', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 487, 'name': 'Data Cache', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 489, 'name': 'DataWorks', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 491, 'name': 'Dialog', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 493,
  'name': 'Document Conversion',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 495,
  'name': 'Geospatial Analytics',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 497,
  'name': 'IBM Alert Notification',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 499,
  'name': 'IBM Bluemix Liberty for Java',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 501,
  'name': 'IBM Bluemix Node.js',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 503,
  'name': 'IBM Bluemix Platform Runtime',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 505,
  'name': 'IBM Containers for Bluemix',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 507,
  'name': 'Internet of Things Platform',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 509,
  'name': 'Language Translation',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 511, 'name': 'Message Hub', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 513,
  'name': 'Mobile Application Content Manager',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 515,
  'name': 'Mobile Quality Assurance',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 517, 'name': 'MQ Light', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 519,
  'name': 'Natural Language Classifier',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 521,
  'name': 'Personality Insights',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 523,
  'name': 'Predictive Analytics',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 525,
  'name': 'Retrieve and Rank',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 527, 'name': 'Secure Gateway', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 529, 'name': 'Session Cache', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 531, 'name': 'Single Sign On', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 533, 'name': 'Speech To Text', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 535, 'name': 'SQL Database', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 537,
  'name': 'Streaming Analytics',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 539, 'name': 'Text to Speech', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 541,
  'name': 'Tradeoff Analytics',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 543,
  'name': 'Virtual Private Network (VPN)',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 545, 'name': 'Workflow', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 547,
  'name': 'Workload Scheduler',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 549,
  'name': 'Virtual Datacenter',
  'type': {'keyName': 'ADDITIONAL_SERVICES_VIRTUAL_DATACENTER'}},
 {'description': 'Dual E5-2600 v4 Series (4 Drives)',
  'id': 551,
  'name': 'Dual E5-2600 v4 Series (4 Drives)',
  'server': ['Dual Intel Xeon E5-2620 v4 (16 Cores, 2.10 GHz)',
             'Dual Intel Xeon E5-2690 v4 (28 Cores, 2.60 GHz)',
             'Dual Intel Xeon E5-2650 v4 (24 Cores, 2.20 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'description': 'Dual E5-2600 v4 Series (12 Drives)',
  'id': 553,
  'name': 'Dual E5-2600 v4 Series (12 Drives)',
  'server': ['Dual Intel Xeon E5-2650 v4 (24 Cores, 2.20 GHz)',
             'Dual Intel Xeon E5-2690 v4 (28 Cores, 2.60 GHz)',
             'Dual Intel Xeon E5-2620 v4 (16 Cores, 2.10 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'description': 'Dual E5-2600 v4 Series (36 Drives)',
  'id': 555,
  'name': 'Dual E5-2600 v4 Series (36 Drives)',
  'server': ['Dual Intel Xeon E5-2620 v4 (16 Cores, 2.10 GHz)',
             'Dual Intel Xeon E5-2690 v4 (28 Cores, 2.60 GHz)',
             'Dual Intel Xeon E5-2650 v4 (24 Cores, 2.20 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'id': 557,
  'name': 'Firewall',
  'type': {'keyName': 'ADDITIONAL_SERVICES_FIREWALL'}},
 {'id': 559,
  'name': 'Global IP Addresses',
  'type': {'keyName': 'ADDITIONAL_SERVICES_GLOBAL_IP_ADDRESSES'}},
 {'id': 561,
  'name': 'ASP.NET Core for Bluemix',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 563,
  'name': 'Testdroid Cloud',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 565,
  'name': 'Network Security Groups',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 567, 'name': 'Blockchain', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 569,
  'name': 'IBM Bluemix Virtual Server',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 571,
  'name': 'Network VLAN',
  'type': {'keyName': 'ADDITIONAL_SERVICES_NETWORK_VLAN'}},
 {'id': 573,
  'name': 'Visual Recognition',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 575,
  'name': 'BigInsights for Apache Hadoop (Subscription)',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 577, 'name': 'Conversation', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 579, 'name': 'Block Storage', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 581, 'name': 'Active Deploy', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 585,
  'name': 'Runtime for Swift',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 587,
  'name': 'Compose for Elasticsearch',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 589,
  'name': 'Compose for etcd',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 591,
  'name': 'Compose for MongoDB',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 593,
  'name': 'Availability Monitoring',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 595,
  'name': 'Globalization Pipeline',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 597,
  'name': 'New Customer Setup',
  'type': {'keyName': 'ADDITIONAL_SERVICES_NEW_CUSTOMER_SETUP'}},
 {'id': 599, 'name': 'AT&T M2X', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 601, 'name': 'Lift', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 605,
  'name': 'Language Translator',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 607,
  'name': 'Compose for PostgreSQL',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 609,
  'name': 'IoT for Automotive',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 611,
  'name': 'Compose for Redis',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 613,
  'name': 'Compose for RabbitMQ',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 615,
  'name': 'Compose for RethinkDB',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 621,
  'name': 'Mobile Analytics',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 623,
  'name': 'Mobile App Builder',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 625, 'name': 'Mobile Data', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 627, 'name': 'Push', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 629,
  'name': 'Continuous Delivery',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 631,
  'name': 'AppScan Dynamic Analyzer',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 633,
  'name': 'AppScan Mobile Analyzer',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 635,
  'name': 'Question and Answer',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 639,
  'name': 'IBM Runbook Automation',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 641, 'name': 'Single Sign On', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 643,
  'name': 'Mobile Application Security',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 645, 'name': 'Discovery', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 647, 'name': 'MongoLab', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 649,
  'name': 'IoT for Insurance',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 651, 'name': 'Object Storage', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 653,
  'name': 'Concept Expansion',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 655,
  'name': 'Time Series Database',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 661,
  'name': 'Decision Optimization',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 665,
  'name': 'dashDB for Transactions SQL Database',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 669,
  'name': 'XpertRule Decision Automation',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 671,
  'name': 'APIs from Pitney Bowes',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 673,
  'name': 'Mobile Foundation ProdTest',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 675,
  'name': 'CDN Addon',
  'type': {'keyName': 'ADDITIONAL_SERVICES_CDN_ADDON'}},
 {'id': 677,
  'name': 'BigInsights for Apache Hadoop',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 679, 'name': 'Open Whisk', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 681,
  'name': 'IBM DB2 on Cloud',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 683, 'name': 'Hybrid Connect', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 685,
  'name': 'Vantrix Transcoder',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 687,
  'name': 'Internet of Things for Electronics',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 689,
  'name': 'Compose for MySQL',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 691,
  'name': 'Internet of Things for Insurance',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 693, 'name': 'dash DB', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 695,
  'name': 'z/OS as a Service',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 699,
  'name': 'XpertRule Decision & Rules Automation',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 701,
  'name': 'Common Service Broker',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 703,
  'name': 'DevOps Insights',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 705,
  'name': 'IBM App Connect',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 707,
  'name': 'Operations Analytics',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 737,
  'name': 'IBM VMware Cloud Foundation',
  'server': ['Dual Intel Xeon E5-2620 v4 (16 Cores, 2.10 GHz)',
             'Dual Intel Xeon E5-2690 v4 (28 Cores, 2.60 GHz)',
             'Dual Intel Xeon E5-2690 v4 (28 Cores, 2.60 GHz)',
             'Dual Intel Xeon E5-2650 v4 (24 Cores, 2.20 GHz)',
             'Dual Intel Xeon E5-2650 v4 (24 Cores, 2.20 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU_FAST_PROVISION'}},
 {'id': 739, 'name': 'DataWorks', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 741, 'name': 'Event Hub', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 747,
  'name': 'Compose for ScyllaDB',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 753,
  'name': 'Natural Language Understanding',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 755,
  'name': 'Natural Data API',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 757,
  'name': 'Product Insights',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 759,
  'name': 'Storage As A Service (StaaS)',
  'type': {'keyName': 'STORAGE_AS_A_SERVICE'}},
 {'id': 761,
  'name': 'Cloud Event Management',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 763,
  'name': 'Simulated Instrument Analytics',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 765,
  'name': 'Simulated Historical Instrument Analytics',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 767,
  'name': 'Historical Instrument Analytics',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 769,
  'name': 'Instrument Analytics',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 771,
  'name': 'Cloud Automation Manager',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 773,
  'name': 'Investment Portfolio',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 775, 'name': 'Containers', 'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 777,
  'name': 'Apprenda Cloud Platform Alpha Edition',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 791, 'name': 'Private Cloud', 'type': {'keyName': 'PRIVATE_CLOUD'}},
 {'id': 793,
  'name': 'Embeddable Reporting',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 795,
  'name': 'Dual Intel Xeon E5v4 (4 Drives)',
  'type': {'keyName': 'BARE_METAL_CORE'}},
 {'id': 797,
  'name': 'Dual Intel Xeon E5v4 (12 Drives)',
  'type': {'keyName': 'BARE_METAL_CORE'}},
 {'id': 799,
  'name': 'Diffusion Cloud from Push Technology',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 801,
  'name': 'Bluemix Container Service',
  'type': {'keyName': 'VIRTUAL_SERVER_INSTANCE_FOR_SERVICE'}},
 {'id': 805,
  'name': 'Load Balancer As A Service (LBaaS)',
  'type': {'keyName': 'LOAD_BALANCER_AS_A_SERVICE'}},
 {'id': 811,
  'name': 'Kubernetes Cluster',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'description': 'Dedicated Host',
  'id': 813,
  'name': 'Dedicated Host',
  'type': {'keyName': 'DEDICATED_HOST'}},
 {'id': 815,
  'name': 'Data Science Experience',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 817,
  'name': 'Compose Enterprise',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'id': 819,
  'name': 'Container Registry',
  'type': {'keyName': 'BLUEMIX_SERVICE'}},
 {'description': 'Public Virtual Server',
  'id': 835,
  'name': 'Public Virtual Server',
  'type': {'keyName': 'VIRTUAL_SERVER_INSTANCE'}},
 {'description': 'Dual Intel Xeon Processor Scalable family (4 Drives)',
  'id': 837,
  'name': 'Dual Intel Xeon Processor Scalable family (4 Drives)',
  'server': ['Intel Xeon Silver 4110 Processor (16 Cores, 2.1GHz)',
             'Intel Xeon Gold 5120 Processor (24 Cores, 2.2GHz)',
             'Intel Xeon Gold 6140 Processor (36 Cores, 2.3GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'description': 'Dual Intel Xeon Processor Scalable family (12 Drives)',
  'id': 839,
  'name': 'Dual Intel Xeon Processor Scalable family (12 Drives)',
  'server': ['Intel Xeon Gold 5120 Processor (24 Cores, 2.2GHz)',
             'Intel Xeon Silver 4110 Processor (16 Cores, 2.1GHz)',
             'Intel Xeon Gold 6140 Processor (36 Cores, 2.3GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'id': 841,
  'name': 'Mass Data Migration',
  'type': {'keyName': 'MASS_DATA_MIGRATION_SERVICE'}},
 {'description': 'BI.S2.H8000',
  'id': 861,
  'name': 'BI.S2.H8000',
  'server': ['BI.S2.H8400', 'BI.S2.H8800'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'id': 863,
  'name': 'Firewall Appliance',
  'type': {'keyName': 'ADDITIONAL_SERVICES_FIREWALL_APPLIANCE'}},
 {'id': 865,
  'name': 'Network VLAN for Service',
  'type': {'keyName': 'NETWORK_VLAN_FOR_SERVICE'}},
 {'description': 'BI.S2.H4000',
  'id': 885,
  'name': 'BI.S2.H4000',
  'server': ['BI.S2.H4200', 'BI.S2.H4100', 'BI.S2.H4400'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'description': 'BI.S1.NW256 (Operating Systems)',
  'id': 895,
  'name': 'BI.S1.NW32 (OS Options)',
  'server': ['Single Intel Xeon E3-1270 v3 (4 Cores, 3.50 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'description': 'BI.S1.NW256 (Operating Systems)',
  'id': 897,
  'name': 'BI.S1.NW256 (OS Options)',
  'server': ['Dual Intel Xeon E5-2690 v3 (24 Cores, 2.60 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'description': 'BI.S1.NW128 (Operating Systems)',
  'id': 899,
  'name': 'BI.S1.NW128 (OS Options)',
  'server': ['Dual Intel Xeon E5-2690 v3 (24 Cores, 2.60 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'description': 'BI.S1.NW128 VMware Virtualization',
  'id': 901,
  'name': 'BI.S1.NW128 (VMware)',
  'server': ['Dual Intel Xeon E5-2690 v3 (24 Cores, 2.60 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'description': 'BI.S1.NW256 (VMware)',
  'id': 903,
  'name': 'BI.S1.NW256 (VMware)',
  'server': ['Dual Intel Xeon E5-2690 v3 (24 Cores, 2.60 GHz)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'id': 905,
  'name': 'Direct Link',
  'type': {'keyName': 'ADDITIONAL_SERVICES_NETWORK_INTERCONNECT'}},
 {'id': 907,
  'name': 'Service Addons',
  'type': {'keyName': 'ADDITIONAL_SERVICES_SERVICE_ADDONS'}},
 {'description': 'Additional Services: Content Delivery Network Service',
  'id': 909,
  'name': 'Content Delivery Network Service',
  'type': {'keyName': 'ADDITIONAL_SERVICES_CDN_SERVICE'}},
 {'description': 'Single E3-1270 v6',
  'id': 911,
  'name': 'Single E3-1270 v6',
  'server': ['XEON - E3-1270-v6 Quad Core - KabyLake : 3.8GHz'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'description': 'BI.S2.NW512 (OS Options)',
  'id': 913,
  'name': 'BI.S2.NW512 (OS Options)',
  'server': ['BI.S2.NW512 (OS Options)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'description': 'BI.S2.NW512 (VMware)',
  'id': 915,
  'name': 'BI.S2.NW512 (VMware)',
  'server': ['BI.S2.NW512 (VMware)'],
  'type': {'keyName': 'BARE_METAL_CPU'}},
 {'id': 931,
  'name': 'Cloud Object Storage',
  'type': {'keyName': 'BLUEMIX_SERVICE'}}]
